import { describe, expect, test } from "bun:test";
import { withTestSite } from "#test/test-site-factory.js";

describe("sitemap", () => {
  test("sitemap.xml is generated by the build", async () => {
    await withTestSite({ files: [] }, (site) => {
      expect(site.hasOutput("sitemap.xml")).toBe(true);
    });
  });

  test("sitemap includes regular pages", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "pages/about.md",
            frontmatter: { title: "About", permalink: "/about/" },
            content: "About page",
          },
        ],
      },
      (site) => {
        const sitemap = site.getOutput("sitemap.xml");
        expect(sitemap.includes("/about/")).toBe(true);
      },
    );
  });

  test("sitemap excludes pages with no_index: true", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "pages/visible.md",
            frontmatter: { title: "Visible", permalink: "/visible/" },
            content: "Visible page",
          },
          {
            path: "pages/hidden.md",
            frontmatter: {
              title: "Hidden",
              permalink: "/hidden/",
              no_index: true,
            },
            content: "Hidden page",
          },
        ],
      },
      (site) => {
        const sitemap = site.getOutput("sitemap.xml");
        expect(sitemap.includes("/visible/")).toBe(true);
        expect(sitemap.includes("/hidden/")).toBe(false);
      },
    );
  });

  test("sitemap escapes ampersands in URLs", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "pages/q.md",
            frontmatter: {
              title: "Query",
              permalink: "/search/?q=cats&p=1",
            },
            content: "Query page",
          },
        ],
      },
      (site) => {
        const sitemap = site.getOutput("sitemap.xml");
        // Raw `&` would make the sitemap invalid XML; it must be escaped.
        expect(sitemap.includes("?q=cats&amp;p=1")).toBe(true);
        expect(sitemap.includes("?q=cats&p=1")).toBe(false);
      },
    );
  });

  test("no_index page is still rendered as a standalone page", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "pages/secret.md",
            frontmatter: {
              title: "Secret Page",
              permalink: "/secret/",
              no_index: true,
            },
            content: "Secret content",
          },
        ],
      },
      (site) => {
        expect(site.hasOutput("secret/index.html")).toBe(true);
        const html = site.getOutput("secret/index.html");
        expect(html.includes("Secret Page")).toBe(true);
      },
    );
  });
});
