name: Test

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Fast Build Test
    runs-on: ubicloud-standard-8
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Fast build
        run: |
          bun install --frozen-lockfile
          FAST_INACCURATE_BUILDS=1 bun scripts/eleventy-build.js
